export const UPDATE_POPUP_BLOCK_ID = 'UPDATE_POPUP_BLOCK_ID'

export const SET_POPUP_VISIBLE = 'SET_POPUP_VISIBLE'

export const UPDATE_POPUP_POS = 'UPDATE_POPUP_POS'

export const UPDATE_SCROLL_POS = 'UPDATE_SCROLL_POS'
